site_name: Econometrics 
site_url: https://pharringtonp19.github.io/econometrics/
site_description: An undergraduate econometric course
site_author: Patrick Power

nav: 
  - Overview:
      - Summary: index.md
  - Topics:
      - Approximation:
        - Introduction: "chapters/approximation/introduction.md"
        - Asymptotics: "chapters/approximation/asymptotics.md"
        - Curse of Dimensionality: "chapters/approximation/curse_of_dimensionality.md"
        - Kernels: "chapters/approximation/kernels.md"
        - Clusters: "chapters/approximation/clusters.md"
      - Optimization:
        - Introduction: "chapters/optimization/introduction.md"
        - Differentiation: "chapters/optimization/differentiation.md"
        - Overparameterization: "chapters/optimization/overparam.md"
      - Probability Theory: 
        - Introduction: "chapters/probability theory/introduction.md"
        - Convergence: "chapters/probability theory/convergence.md"
        - Conditioning: "chapters/probability theory/conditioning.md"
      - Programming: 
        - Introduction: "chapters/programming/introduction.md"

theme:
  name: material
  palette:
    scheme: default
    primary: deep blue
  icon:
    admonition:
      code: fontawesome/solid/code
      note: octicons/tag-16
  features:
    #- navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - navigation.top

markdown_extensions:
    - codehilite
    - attr_list
    - md_in_html
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - admonition
    - pymdownx.details
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - footnotes
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

extra_javascript: 
    # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

